from enum import StrEnum


class AccountStatus(StrEnum):
    PENDING_EMAIL = "PENDING_EMAIL"
    PENDING_MATRIX = "PENDING_MATRIX"
    ACTIVE = "ACTIVE"
    SUSPENDED = "SUSPENDED"
    DISABLED = "DISABLED"


class RoleCode(StrEnum):
    USER = "USER"
    SUPPORT_AGENT = "SUPPORT_AGENT"
    FINANCE_SUPPORT = "FINANCE_SUPPORT"
    SUPPORT_SUPERVISOR = "SUPPORT_SUPERVISOR"
    SUPER_ADMIN = "SUPER_ADMIN"


class HoldType(StrEnum):
    WITHDRAWAL = "WITHDRAWAL"
