upstream synapse_upstream {
    server synapse:8008;
}

upstream element_upstream {
    server element-web:80;
}

server {
    listen 80;
    server_name {{PUBLIC_HOSTNAME}};
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name {{PUBLIC_HOSTNAME}};

    ssl_certificate /etc/nginx/certs/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/privkey.pem;

    location = /.well-known/matrix/client {
        default_type application/json;
        add_header Access-Control-Allow-Origin *;
        return 200 '{"m.homeserver":{"base_url":"{{SYNAPSE_PUBLIC_BASEURL}}"}}';
    }

    location /_matrix/ {
        proxy_pass http://synapse_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }

    location / {
        proxy_pass http://element_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}

