// Top-level build file where you can add configuration options common to all sub-projects/modules.
apply from: "config.gradle"

allprojects {
    repositories {
        maven { url 'https://jitpack.io' }
        maven {
            url "https://mvn.getui.com/nexus/content/repositories/releases/"
        }
        maven {
            url "http://192.168.17.217:8081/nexus/content/repositories/snapshots/"
            allowInsecureProtocol = true
        }

        mavenCentral()
        google()
    }
}

subprojects {
    tasks.register('prepareKotlinBuildScriptModel') {
        description = 'Compatibility task for Android Studio Gradle sync.'
    }
}
