import 'package:flutter/cupertino.dart';
import 'package:matrix/matrix.dart';
import 'matrix_e2ee_client.dart';

class MatrixHomePage extends StatefulWidget { const MatrixHomePage({super.key, required this.matrix}); final MatrixSdkE2eeClient matrix; @override State<MatrixHomePage> createState()=>_MatrixHomePageState(); }
class _MatrixHomePageState extends State<MatrixHomePage> {
  bool syncing=false;
  Future<void> sync() async { if(syncing)return; setState(()=>syncing=true); try{await widget.matrix.sync();} finally{if(mounted)setState(()=>syncing=false);} }
  @override void initState(){super.initState(); sync();}
  @override Widget build(BuildContext context){ final rooms=widget.matrix.sdkClient.rooms; final items=<Widget>[]; for(final room in rooms){ items.add(CupertinoListTile(title:Text(room.getLocalizedDisplayname()),subtitle:Text(room.lastEvent?.text??'端到端加密消息'),onTap:()=>Navigator.push(context,CupertinoPageRoute(builder:(_)=>RoomPage(room:room,roomName:room.getLocalizedDisplayname()))))); } if(items.isEmpty)items.add(const CupertinoListTile(title:Text('暂无房间'))); return CupertinoPageScaffold(navigationBar:CupertinoNavigationBar(middle:const Text('消息')),child:SafeArea(child:ListView(padding:const EdgeInsets.all(16),children:[CupertinoListSection.insetGrouped(children:items)]))); }
}
class RoomPage extends StatefulWidget { const RoomPage({super.key,required this.roomName,required this.room}); final String roomName; final Room room; @override State<RoomPage> createState()=>_RoomPageState(); }
class _RoomPageState extends State<RoomPage>{ final input=TextEditingController(); Timeline? timeline; bool sending=false; @override void initState(){super.initState();load();} Future<void> load()async{final t=await widget.room.getTimeline(onUpdate:(){if(mounted)setState((){});});if(mounted)setState(()=>timeline=t);} Future<void> send()async{final text=input.text.trim();if(text.isEmpty)return;setState(()=>sending=true);try{await widget.room.sendTextEvent(text,parseCommands:false);input.clear();}finally{if(mounted)setState(()=>sending=false);}} @override void dispose(){input.dispose();super.dispose();} @override Widget build(BuildContext context){final events=timeline?.events??const <Event>[];return CupertinoPageScaffold(navigationBar:CupertinoNavigationBar(middle:Text(widget.roomName)),child:SafeArea(child:Column(children:[Expanded(child:events.isEmpty?const Center(child:Text('暂无消息')):ListView.builder(reverse:true,itemCount:events.length,itemBuilder:(_,i){final e=events[events.length-1-i];return CupertinoListTile(title:Text(e.senderId),subtitle:Text(e.text));})),CupertinoTextField(controller:input,placeholder:'输入加密消息',onSubmitted:(_)=>send(),padding:const EdgeInsets.all(12)),CupertinoButton.filled(onPressed:sending?null:send,child:sending?const CupertinoActivityIndicator():const Text('发送'))])));}}
