// GENERATED by scripts/prepare_fluent_emojis.py — do not edit.
// Animated Fluent Emojis (c) Tarikul-Islam-Anik, MIT License.
import 'package:characters/characters.dart';

final class FluentEmoji {
  const FluentEmoji({required this.char, required this.name, required this.asset});

  final String char; // unicode sent inside the encrypted text message
  final String name;
  final String asset; // animated WebP bundled with the app
}

const fluentEmojis = <FluentEmoji>[
  FluentEmoji(char: '😄', name: 'grinning', asset: 'assets/emoji/grinning.webp'),
  FluentEmoji(char: '😊', name: 'smile', asset: 'assets/emoji/smile.webp'),
  FluentEmoji(char: '😂', name: 'joy', asset: 'assets/emoji/joy.webp'),
  FluentEmoji(char: '😇', name: 'halo', asset: 'assets/emoji/halo.webp'),
  FluentEmoji(char: '😍', name: 'heart eyes', asset: 'assets/emoji/heart-eyes.webp'),
  FluentEmoji(char: '🥰', name: 'hearts face', asset: 'assets/emoji/hearts-face.webp'),
  FluentEmoji(char: '😘', name: 'kiss', asset: 'assets/emoji/kiss.webp'),
  FluentEmoji(char: '😉', name: 'wink', asset: 'assets/emoji/wink.webp'),
  FluentEmoji(char: '🤪', name: 'zany', asset: 'assets/emoji/zany.webp'),
  FluentEmoji(char: '😋', name: 'savoring', asset: 'assets/emoji/savoring.webp'),
  FluentEmoji(char: '🥲', name: 'holding back tears', asset: 'assets/emoji/holding-back-tears.webp'),
  FluentEmoji(char: '😭', name: 'sob', asset: 'assets/emoji/sob.webp'),
  FluentEmoji(char: '😢', name: 'cry', asset: 'assets/emoji/cry.webp'),
  FluentEmoji(char: '😡', name: 'angry', asset: 'assets/emoji/angry.webp'),
  FluentEmoji(char: '😠', name: 'smiling angry', asset: 'assets/emoji/smiling-angry.webp'),
  FluentEmoji(char: '😎', name: 'cool', asset: 'assets/emoji/cool.webp'),
  FluentEmoji(char: '🤓', name: 'nerd', asset: 'assets/emoji/nerd.webp'),
  FluentEmoji(char: '😌', name: 'relieved', asset: 'assets/emoji/relieved.webp'),
  FluentEmoji(char: '😪', name: 'sleepy', asset: 'assets/emoji/sleepy.webp'),
  FluentEmoji(char: '😴', name: 'sleeping', asset: 'assets/emoji/sleeping.webp'),
  FluentEmoji(char: '😷', name: 'mask', asset: 'assets/emoji/mask.webp'),
  FluentEmoji(char: '🙃', name: 'upside down', asset: 'assets/emoji/upside-down.webp'),
  FluentEmoji(char: '🤫', name: 'shushing', asset: 'assets/emoji/shushing.webp'),
  FluentEmoji(char: '😱', name: 'scream', asset: 'assets/emoji/scream.webp'),
  FluentEmoji(char: '😅', name: 'sweat smile', asset: 'assets/emoji/sweat-smile.webp'),
  FluentEmoji(char: '🤣', name: 'rofl', asset: 'assets/emoji/rofl.webp'),
  FluentEmoji(char: '😐', name: 'neutral', asset: 'assets/emoji/neutral.webp'),
  FluentEmoji(char: '😒', name: 'unamused', asset: 'assets/emoji/unamused.webp'),
  FluentEmoji(char: '🤔', name: 'thinking', asset: 'assets/emoji/thinking.webp'),
  FluentEmoji(char: '😲', name: 'shocked', asset: 'assets/emoji/shocked.webp'),
  FluentEmoji(char: '🥳', name: 'partying', asset: 'assets/emoji/partying.webp'),
  FluentEmoji(char: '🥺', name: 'pleading', asset: 'assets/emoji/pleading.webp'),
  FluentEmoji(char: '👍', name: 'thumbs up', asset: 'assets/emoji/thumbs-up.webp'),
  FluentEmoji(char: '👎', name: 'thumbs down', asset: 'assets/emoji/thumbs-down.webp'),
  FluentEmoji(char: '👌', name: 'ok hand', asset: 'assets/emoji/ok-hand.webp'),
  FluentEmoji(char: '👋', name: 'wave', asset: 'assets/emoji/wave.webp'),
  FluentEmoji(char: '👏', name: 'clap', asset: 'assets/emoji/clap.webp'),
  FluentEmoji(char: '🙏', name: 'pray', asset: 'assets/emoji/pray.webp'),
  FluentEmoji(char: '💪', name: 'muscle', asset: 'assets/emoji/muscle.webp'),
  FluentEmoji(char: '❤', name: 'heart', asset: 'assets/emoji/heart.webp'),
  FluentEmoji(char: '💔', name: 'broken heart', asset: 'assets/emoji/broken-heart.webp'),
  FluentEmoji(char: '✨', name: 'sparkles', asset: 'assets/emoji/sparkles.webp'),
  FluentEmoji(char: '🎉', name: 'party popper', asset: 'assets/emoji/party-popper.webp'),
  FluentEmoji(char: '🎂', name: 'cake', asset: 'assets/emoji/cake.webp'),
  FluentEmoji(char: '🌹', name: 'rose', asset: 'assets/emoji/rose.webp'),
  FluentEmoji(char: '🎁', name: 'gift', asset: 'assets/emoji/gift.webp'),
  FluentEmoji(char: '☕', name: 'coffee', asset: 'assets/emoji/coffee.webp'),
  FluentEmoji(char: '🍺', name: 'beer', asset: 'assets/emoji/beer.webp'),
  FluentEmoji(char: '🍉', name: 'watermelon', asset: 'assets/emoji/watermelon.webp'),
  FluentEmoji(char: '🍓', name: 'strawberry', asset: 'assets/emoji/strawberry.webp'),
  FluentEmoji(char: '🐶', name: 'dog', asset: 'assets/emoji/dog.webp'),
  FluentEmoji(char: '🐱', name: 'cat', asset: 'assets/emoji/cat.webp'),
  FluentEmoji(char: '🐷', name: 'pig', asset: 'assets/emoji/pig.webp'),
  FluentEmoji(char: '🔥', name: 'fire', asset: 'assets/emoji/fire.webp'),
  FluentEmoji(char: '🚀', name: 'rocket', asset: 'assets/emoji/rocket.webp'),
  FluentEmoji(char: '🥇', name: 'medal', asset: 'assets/emoji/medal.webp'),
];

final Map<String, FluentEmoji> _fluentEmojisByChar = {
  for (final emoji in fluentEmojis) emoji.char: emoji,
};

FluentEmoji? fluentEmojiByChar(String char) => _fluentEmojisByChar[char];

/// 消息"纯动效表情"判定：全部字素为已知 Fluent 表情（允许空白），
/// 且表情数量 1–4。满足时消息以放大动画渲染；否则按普通文本渲染。
List<FluentEmoji> fluentEmojisInMessage(String text) {
  final emojis = <FluentEmoji>[];
  for (final grapheme in text.characters) {
    if (grapheme.trim().isEmpty) continue;
    final emoji = _fluentEmojisByChar[grapheme];
    if (emoji == null) return const [];
    emojis.add(emoji);
    if (emojis.length > 4) return const [];
  }
  return emojis;
}
