#!/usr/bin/env python3
"""Freeze existing licensed WebP sources into a content-addressed resource set.
No network, publication, ZIP extraction, or source file deletion.
"""
import argparse
import hashlib
import json
import re
from pathlib import Path


def generate(root: Path, destination: Path) -> dict:
    mobile = root / 'apps/mobile_flutter'
    catalog = (mobile / 'lib/features/emoji/fluent_emoji_catalog.dart').read_text(encoding='utf-8')
    paths = re.findall(r"asset: 'assets/emoji/([^']+\.webp)'", catalog)
    assert len(paths) == 56 and len(set(paths)) == 56
    entries = []
    for name in paths:
        payload = (mobile / 'assets/emoji' / name).read_bytes()
        assert payload[:4] == b'RIFF' and payload[8:12] == b'WEBP'
        assert len(payload) <= 1024 * 1024
        entries.append({'id': name[:-5], 'path': name, 'sha256': hashlib.sha256(payload).hexdigest(),
                        'bytes': len(payload), 'type': 'image/webp'})
    revision = hashlib.sha256(json.dumps(entries, sort_keys=True, separators=(',', ':')).encode()).hexdigest()[:24]
    manifest = {'version': 1, 'revision': revision, 'entries': entries}
    encoded = json.dumps(manifest, ensure_ascii=False, sort_keys=True, separators=(',', ':'))
    digest = hashlib.sha256(encoded.encode()).hexdigest()
    target = destination / revision
    target.mkdir(parents=True, exist_ok=True)
    for entry in entries:
        (target / entry['path']).write_bytes((mobile / 'assets/emoji' / entry['path']).read_bytes())
    (target / 'manifest.json').write_text(encoded, encoding='utf-8')
    (target / 'NOTICE.txt').write_bytes((mobile / 'assets/emoji/NOTICE.txt').read_bytes())
    (target / 'ANIMATED_SOURCE_LICENSE.txt').write_bytes((mobile / 'assets/emoji/ANIMATED_SOURCE_LICENSE.txt').read_bytes())
    generated = mobile / 'lib/features/emoji/emoji_resource_manifest.dart'
    generated.write_text('// GENERATED by scripts/build_emoji_resources.py. Licensed source files remain fixtures.\n'
                         f"const emojiManifestDigest = '{digest}';\n"
                         f"const emojiManifestJson = r'''{encoded}''';\n", encoding='utf-8')
    return {'revision': revision, 'manifestSha256': digest, 'files': len(entries),
            'bytes': sum(e['bytes'] for e in entries), 'directory': str(target)}

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--root', type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument('--output', type=Path, required=True)
    args = parser.parse_args()
    print(json.dumps(generate(args.root, args.output), indent=2))
