"""Moments social domain."""
from alembic import op
import sqlalchemy as sa
revision='0013_moments';down_revision='0012_friendship';branch_labels=None;depends_on=None
def upgrade():
    op.create_table('moments',sa.Column('id',sa.String(36),primary_key=True),sa.Column('author_id',sa.String(36),sa.ForeignKey('users.id'),nullable=False),sa.Column('text',sa.Text(),nullable=False),sa.Column('visibility',sa.String(30),nullable=False),sa.Column('image_urls',sa.JSON(),nullable=False),sa.Column('include_user_ids',sa.JSON(),nullable=False),sa.Column('exclude_user_ids',sa.JSON(),nullable=False),sa.Column('location',sa.String(255)),sa.Column('link_url',sa.String(2048)),sa.Column('status',sa.String(30),nullable=False),sa.Column('idempotency_key',sa.String(128),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('deleted_at',sa.DateTime(timezone=True)),sa.UniqueConstraint('author_id','idempotency_key',name='uq_moment_idempotency'))
    op.create_table('moment_likes',sa.Column('id',sa.String(36),primary_key=True),sa.Column('moment_id',sa.String(36),sa.ForeignKey('moments.id'),nullable=False),sa.Column('user_id',sa.String(36),sa.ForeignKey('users.id'),nullable=False),sa.Column('idempotency_key',sa.String(128),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('moment_id','user_id',name='uq_moment_like'),sa.UniqueConstraint('user_id','idempotency_key',name='uq_moment_like_idempotency'))
    op.create_table('moment_comments',sa.Column('id',sa.String(36),primary_key=True),sa.Column('moment_id',sa.String(36),sa.ForeignKey('moments.id'),nullable=False),sa.Column('user_id',sa.String(36),sa.ForeignKey('users.id'),nullable=False),sa.Column('parent_id',sa.String(36)),sa.Column('text',sa.Text(),nullable=False),sa.Column('idempotency_key',sa.String(128),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('deleted_at',sa.DateTime(timezone=True)),sa.UniqueConstraint('user_id','idempotency_key',name='uq_moment_comment_idempotency'))
def downgrade():
    for table in ('moment_comments','moment_likes','moments'):op.drop_table(table)
